### ISSUE TITLE
Can't connect to local MySQL server

### ISSUE THREAD

**Issue by leymannx** [keopx/docker-lamp#13]
I tried to install Drupal from a fresh clone but when it comes to DB credentials it fails:

> Failed to connect to your database server. The server reports the following message: SQLSTATE[HY000] [2002] No such file or directory.

Steps performed
- `$ git clone https://github.com/keopx/docker-lamp keopx`
- `$ cd keopx/data`
- `$ rm -rf www`
- `$ drush dl (local Drush on my Mac)`
- `$ mv drupal-8.4.4 www`
- `$ docker-compose up -d`
- everything fine, no error
- Browser: http://localhost:8008
- run installation routine
- then stops on DB connection (UN: drupaluser, PW: drupalpass, DB: drupal) with above error
 
I then tried
- `$ docker exec -ti keopx_web_1 bash`
- inside I tried: `$ mysql -uroot -proot`
- Follwing error:

> ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2 "No such file or directory")

Do have to perform anything extra before the MySQL container is available to the web container?

**Comment by leymannx** [comment]
Whereas PHPMyAdmin and the MySQL container itself runs just fine.

**Comment by keopx** [comment]
@leymannx the container that has MySQL is keopx_mysql_1. 

If you connect remotly <code>$ mysql -hmysql -uroot -proot</code> from any docker container (e.i. keopx_web_1)

@leymannx another thing, when you connect Drupal to MySQL, use _mysql_ instead _localhost_

**Comment by leymannx** [comment]
![screenshot 2018-01-09 15 02 26](https://user-images.githubusercontent.com/3585653/34724464-29aa31c8-f54e-11e7-923e-02b374c7bdb1.png)

**Comment by leymannx** [comment]
Thanks a lot! That did the trick.

**Comment by keopx** [comment]
@leymannx Docker resolve internally docker name as hostname

**Comment by leymannx** [comment]
That was the point I missed. Thanks a lot again!
