### ISSUE TITLE
Error al activar xdebug

### ISSUE THREAD

**Issue by oskarcalvo** [keopx/docker-lamp#18]
Cuando se descomenta la línea:

`- ./config/php/xdebug.ini:/etc/php/${PHP_VERSION}/apache2/conf.d/20-xdebug.ini`

devuelve el siguiente error:

`web_1         | rm: cannot remove '/etc/php/7.1/apache2/conf.d/20-xdebug.ini': Device or resource busy
`

**Comment by keopx** [comment]
Por ahora prueba:

```yml
environment:
  - XDEBUG_ENABLED=1
```

**Comment by keopx** [comment]
Resolved, read: [README.md#xdebug](https://github.com/keopx/docker-lamp/blob/master/README.md#xdebug)
