### ISSUE TITLE
phpmyadmin exceeds the limit of 2097152 bytes

### ISSUE THREAD

**Issue by kwipers** [keopx/docker-lamp#23]
Warning: POST Content-Length of 202642898 bytes exceeds the limit of 2097152 bytes in Unknown on line 0

How to increase the limit of memory sql can store?

**Comment by keopx** [comment]
@kwipers You can change this file to update: [config/mysql/my.cnf](https://github.com/keopx/docker-lamp/blob/master/config/mysql/my.cnf)
