### ISSUE TITLE
[Documentar] Usuario local identico al usuario de docker

### ISSUE THREAD

**Issue by keopx** [keopx/docker-lamp#5]
Para evitar esta configuración tan compleja, creo que es interesante esto:

Añadir el siguiente usuario:

```RUN useradd me```

Con esto conseguimos un usuario con uid 1000. Que quiere decir esto, pues que este usuario es el equivalente al usuario de nuestra maquina con uid 1000. Por tanto al ejecutar bash ejecutaríamos como si fuese nuestro usuario local.

Para ejecutar el bash lo haríamos así:

```$ docker exec --user='me' -it {nombre_contenedor} bash```

De esta manera simplificamos el entorno de configuración y evitamos tener que hacer todas esas operaciones fuera del contenedor.

Igual es muy loco todo esto, pero creo que esto simplificaría el proceso.

PD: también se podría añadir el usuario al grupo www-data si fuese necesario.

```usermod -G www-data -a me```

Referencia:

* https://forums.docker.com/t/swiching-between-root-and-non-root-users-from-interactive-console/2269/5

**Comment by isholgueras** [comment]
Esto me está funcionando sin problemas. Cuando configuro los permisos como `chown -R isholgueras:www-data web` me lo configura dentro del contenedor como
`me:www-data`.

Con esto no tengo que entrar en el contenedor para casi nada.

**Comment by keopx** [comment]
new user is keopx:
`docker-compose exec --user=keopx web bash` 
`docker-compose exec --user=keopx web drush` 
`docker-compose exec --user=keopx web composer`
